#ifndef NCNN_YOLOV5X_SEG_H
#define NCNN_YOLOV5X_SEG_H

#include <stdint.h>

#define NCNN_DYNAMIC_DIM INT64_C(-1)
#define NCNN_MAX_RANK 4
#define NCNN_STATUS_SUCCESS 0
#define NCNN_STATUS_NULL_POINTER 1
#define NCNN_STATUS_INVALID_SHAPE 2
#define NCNN_STATUS_CONSTRAINT_VIOLATION 3
#define NCNN_STATUS_SHAPE_ARITHMETIC_OVERFLOW 4
#define NCNN_STATUS_OUTPUT_CAPACITY_INSUFFICIENT 5

typedef uint16_t ncnn_float16_t;
typedef uint16_t ncnn_bfloat16_t;

#define YOLOV5X_SEG_INPUT_COUNT 1
#define YOLOV5X_SEG_OUTPUT_COUNT 2

#define YOLOV5X_SEG_INPUT1_RANK 3
#define YOLOV5X_SEG_INPUT1_DIM0 INT64_C(3)
#define YOLOV5X_SEG_INPUT1_DIM1 INT64_C(640)
#define YOLOV5X_SEG_INPUT1_DIM2 INT64_C(640)
#define YOLOV5X_SEG_INPUT1_DYNAMIC_DIM_MASK UINT32_C(0x0)
#define YOLOV5X_SEG_INPUT1_ELEMENTS UINT64_C(1228800)

#define YOLOV5X_SEG_OUTPUT1_RANK 3
#define YOLOV5X_SEG_OUTPUT1_DIM0 INT64_C(32)
#define YOLOV5X_SEG_OUTPUT1_DIM1 INT64_C(160)
#define YOLOV5X_SEG_OUTPUT1_DIM2 INT64_C(160)
#define YOLOV5X_SEG_OUTPUT1_DYNAMIC_DIM_MASK UINT32_C(0x0)
#define YOLOV5X_SEG_OUTPUT1_ELEMENTS UINT64_C(819200)
#define YOLOV5X_SEG_OUTPUT1_SHAPE_DEPENDS_ON_DATA 0

#define YOLOV5X_SEG_OUTPUT2_RANK 2
#define YOLOV5X_SEG_OUTPUT2_DIM0 INT64_C(25200)
#define YOLOV5X_SEG_OUTPUT2_DIM1 INT64_C(117)
#define YOLOV5X_SEG_OUTPUT2_DYNAMIC_DIM_MASK UINT32_C(0x0)
#define YOLOV5X_SEG_OUTPUT2_ELEMENTS UINT64_C(2948400)
#define YOLOV5X_SEG_OUTPUT2_SHAPE_DEPENDS_ON_DATA 0


#ifdef __cplusplus
extern "C" {
#endif

int yolov5x_seg(const float *input1, float *output1, float *output2);

#ifdef __cplusplus
}
#endif

#endif  // NCNN_YOLOV5X_SEG_H
