#ifndef NCNN_EFFICIENTNET_B3_H
#define NCNN_EFFICIENTNET_B3_H

#include <stdint.h>

#define NCNN_DYNAMIC_DIM INT64_C(-1)
#define NCNN_MAX_RANK 4
#define NCNN_STATUS_SUCCESS 0
#define NCNN_STATUS_NULL_POINTER 1
#define NCNN_STATUS_INVALID_SHAPE 2
#define NCNN_STATUS_CONSTRAINT_VIOLATION 3
#define NCNN_STATUS_SHAPE_ARITHMETIC_OVERFLOW 4
#define NCNN_STATUS_OUTPUT_CAPACITY_INSUFFICIENT 5

typedef uint16_t ncnn_float16_t;
typedef uint16_t ncnn_bfloat16_t;

#define EFFICIENTNET_B3_INPUT_COUNT 1
#define EFFICIENTNET_B3_OUTPUT_COUNT 1

#define EFFICIENTNET_B3_INPUT1_RANK 3
#define EFFICIENTNET_B3_INPUT1_DIM0 INT64_C(3)
#define EFFICIENTNET_B3_INPUT1_DIM1 INT64_C(300)
#define EFFICIENTNET_B3_INPUT1_DIM2 INT64_C(300)
#define EFFICIENTNET_B3_INPUT1_DYNAMIC_DIM_MASK UINT32_C(0x0)
#define EFFICIENTNET_B3_INPUT1_ELEMENTS UINT64_C(270000)

#define EFFICIENTNET_B3_OUTPUT1_RANK 1
#define EFFICIENTNET_B3_OUTPUT1_DIM0 INT64_C(1000)
#define EFFICIENTNET_B3_OUTPUT1_DYNAMIC_DIM_MASK UINT32_C(0x0)
#define EFFICIENTNET_B3_OUTPUT1_ELEMENTS UINT64_C(1000)
#define EFFICIENTNET_B3_OUTPUT1_SHAPE_DEPENDS_ON_DATA 0


#ifdef __cplusplus
extern "C" {
#endif

int efficientnet_b3(const float *input1, float *output1);

#ifdef __cplusplus
}
#endif

#endif  // NCNN_EFFICIENTNET_B3_H
