name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    strategy:
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]   # x86_64 和 ARM64
      fail-fast: false   # 可选：一个架构失败不影响另一个

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout compiler
        uses: actions/checkout@v4
        with:
          path: compiler
          submodules: true

      - name: Install LLVM 21
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-21 main"
          sudo apt-get update
          sudo apt-get install -y llvm-21-dev libllvm-21-ocaml-dev libllvm21 llvm-21 llvm-21-dev llvm-21-doc llvm-21-examples llvm-21-runtime clang-21 clang-tools-21 clang-21-doc libclang-common-21-dev libclang-21-dev libclang1-21 clang-format-21 python3-clang-21 clangd-21 clang-tidy-21 libc++-21-dev libc++abi-21-dev libomp-21-dev libmlir-21-dev mlir-21-tools

      - name: Install dependencies
        run: sudo apt-get install -y cmake libgtest-dev

      - name: Build
        run: |
          cmake -S compiler -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_DIR=/usr/lib/llvm-21/lib/cmake/llvm
          cmake --build build

      - name: Check formatting
        run: cmake --build build --target format_check

      - name: Run clang-tidy
        run: cmake --build build --target tidy

      - name: Test
        run: ctest --test-dir build --output-on-failure -j$(nproc)

      - name: Build with ASan and UBSan
        run: |
          cmake -S compiler -B build-sanitize \
            -DCMAKE_BUILD_TYPE=Debug \
            -DLLVM_DIR=/usr/lib/llvm-21/lib/cmake/llvm \
            -DCMAKE_C_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer" \
            -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer" \
            -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address,undefined" \
            -DCMAKE_SHARED_LINKER_FLAGS="-fsanitize=address,undefined"
          cmake --build build-sanitize

      - name: Test with ASan and UBSan once
        run: ctest --test-dir build-sanitize --output-on-failure -j$(nproc)